### ISSUE TITLE
user-defined float functions do not take 3 arguments, throws error on 2nd arg

### ISSUE THREAD

**Issue by jmichae3** [POV-Ray/povray#334] opened 2017-10-14 20:56 UTC
### Summary

user-defined float functions do not take 3 arguments

### Environment

  - Source code Git tag: v3.7.0.0
  - POV-Ray version: v3.7.0+msvc10.win64
  - Operating system: Windows 7
  - Hardware platform: x86-64
  - Compiler: 
  - Regression from: 

### Steps to Reproduce

 1. `#declare func=function(a,b,c){(a*12)+b*15+c*27)}`
 2. `#local d=func(1,2,3);`

### Expected Behavior

should work

### Actual Behavior

Parse Error: Expected 'numeric Expression', undeclared identifier 'b' found instead

### Scene

~~~
#declare func=function(a,b,c){(a*12)+b*15+c*27)}
#local d=func(1,2,3);
~~~

### Output

~~~
Parse Error: Expected 'numeric Expression', undeclared identifier 'b' found instead
~~~

### Suggested Solution

make user-defined functions work with any number of arguments

**Comment by c-lipka** [comment] 2017-10-15 15:04
Took the liberty to re-format pieces of your report to be legible.

Please _do preview your issue report_ before submitting it. You may also want to read up on GitHub's Markdown syntax (see the link "Styling with Markdown is supported" below the text entry field).

**Comment by c-lipka** [comment] 2017-10-15 15:09
Can't reproduce. With the suggested "steps to reproduce", I'm instead seeing `Parse Error: No matching } in ')', ) found instead`.

Please take more time to write and verify your issue reports!

Normally I'd give you the opportunity to submit an update to your issue report; however, since this issue report also strongly smells like a user error, I'm closing it outright.

**Do visit our newsgroups for support!**

**Closed by c-lipka** 2017-10-15 15:09 UTC
